name: xcube-geodb-openeo
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.8,<3.10
  # Required
  - geopandas
  - pandas
  - shapely
  - xcube >= 1.1.1
  - xcube_geodb >= 1.0.5
  - geojson
  - yaml
  - ipython
  - urllib3
  - openeo
  - requests
  # Testing
  - pytest >=4.4
  - pytest-cov >=2.6
  - requests-mock >=1.8
