name: xcube-geodb-openeo
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.8
  # Required
  - cryptography
  - ipython
  - geojson
  - geopandas
  - openeo
  - pandas
  - pyjwt
  - python-dotenv
  - pytz
  - urllib3
  - requests
  - shapely
  - xcube >= 1.1.1
  - xcube_geodb >= 1.1.0
  - yaml
  # Testing
  - pytest >=4.4
  - pytest-cov >=2.6
  - requests-mock >=1.8
